epg:
  cache-dir: /var/lib/mirakc/epg

server:
  # Replace `localhost` with `0.0.0.0` (ipv4) or `::` (ipv6) if you like to
  # connect from other hosts.
  addrs:
    - http: '0.0.0.0:40772'

tuners:
  # Use a Mirakurun-compatible server as a tuner.
  #- name: mirakc
  #  types: [GR, BS]
  #  command: >-
  #    curl -sG http://mirakc:40772/api/channels/{{{channel_type}}}/{{{channel}}}/stream?decode=0
  # Normally, you need to define a tuner for each device like below:
  - name: PT3-S1
    types: [BS, CS]
    command:  >-
      recpt1 --device /dev/pt3video0 {{{channel}}} - -
  - name: PT3-S2
    types: [BS, CS]
    command: >-
      recpt1 --device /dev/pt3video1 {{{channel}}} - -
  - name: PT3-T1
    types: [GR]
    command: >-
      recpt1 --device /dev/pt3video2 {{{channel}}} - -
  - name: PT3-T2
    types: [GR]
    command: >-
      recpt1 --device /dev/pt3video3 {{{channel}}} - -

filters:
  # Optionally, you can specify a command to process TS packets before sending
  # them to a client.
  #
  # The following command processes TS packets on a remote server listening on
  # TCP port 40774.
  # decode-filter:
  #   command: >-
  #     socat -,cool-write tcp-connect:remote:40774
  #
  # Chinachu/Mirakurunの設定例より
  #
  # tsukumijima/libaribb25を使用する場合は，`arib-b25-stream-test -v 0`とログを
  # 制限する必要があります．これはSTDERRへの出力で`\r`が使用されており，これが原
  # 因でログのライン分割処理で問題が発生するためです．
  decode-filter:
    command: >-
      arib-b25-stream-test -v 0

# Change the following channel settings according to your environment.
channels:
  # 地上波
  - name: ＮＨＫＥテレ
    type: GR
    channel: '18'
  - name: 鹿児島讀賣テレビ
    type: GR
    channel: '29'
  - name: ＮＨＫ総合
    type: GR
    channel: '34'
  - name: ＫＫＢ鹿児島放送
    type: GR
    channel: '36'
  - name: ＭＢＣ南日本放送
    type: GR
    channel: '40'
  - name: 鹿児島テレビ放送
    type: GR
    channel: '42'

  # BS (無料)
  - name: NHK BS
    type: BS
    channel: BS15_0
    services: [101]
  - name: BS日テレ
    type: BS
    channel: BS13_0
    services: [141]
  - name: BS朝日
    type: BS
    channel: BS01_0
    services: [151]
  - name: BS-TBS
    type: BS
    channel: BS01_1
    services: [161]
  - name: BSテレ東
    type: BS
    channel: BS01_2
    services: [171]
  - name: BSフジ
    type: BS
    channel: BS13_1
    services: [181]
  - name: BS10 (200:無料)・BS10スターチャンネル(201:有料)
    type: BS
    channel: BS15_1
    services: [200]
  - name: BS11
    type: BS
    channel: BS09_0
    services: [211]
  - name: TwellV
    type: BS
    channel: BS09_2
    services: [222]
  - name: 放送大学BS
    type: BS
    channel: BS13_2
    services: [231, 232]
    disabled: true

  # BS (有料)
  - name: WOWOWプライム
    type: BS
    channel: BS03_0
    services: [191]
    disabled: true
  - name: WOWOWライブ
    type: BS
    channel: BS05_0
    services: [192]
    disabled: true
  - name: WOWOWシネマ
    type: BS
    channel: BS05_1
    services: [193]
    disabled: true
  - name: グリーンチャンネル
    type: BS
    channel: BS21_2
    services: [234]
    disabled: true
  - name: BSアニマックス
    type: BS
    channel: BS03_1
    services: [236]
    disabled: false
  - name: J SPORTS 1
    type: BS
    channel: BS19_1
    services: [242]
    disabled: true
  - name: J SPORTS 2
    type: BS
    channel: BS19_2
    services: [243]
    disabled: true
  - name: J SPORTS 3
    type: BS
    channel: BS19_3
    services: [244]
    disabled: true
  - name: J SPORTS 4
    type: BS
    channel: BS19_0
    services: [245]
    disabled: true
  - name: BS釣りビジョン
    type: BS
    channel: BS03_2
    services: [251]
    disabled: true
  - name: WOWOWプラス
    type: BS
    channel: BS21_0
    services: [252]
    disabled: true
  - name: 日本映画専門ch
    type: BS
    channel: BS21_1
    services: [255]
    disabled: true
  - name: ディズニーch
    type: BS
    channel: BS23_0
    services: [256]
    disabled: true
  - name: BS松竹東急
    type: BS
    channel: BS23_3
    services: [260]
    disabled: true
  - name: BSよしもと
    type: BS
    channel: BS23_1
    services: [265]
    disabled: true
